#!/bin/bash
#$ -V
#$ -cwd
#$ -o rmvContfromAll_log.txt
#$ -j y
#$ -l mem_free=10G,h_vmem=20G
#$ -pe threaded 12

echo "--------------------------------------------------"
echo "Script starts"
date
echo "--------------------------------------------------"
source config.txt

module load qiime/1.9.1



echo "Begining the filtering of all sequences, producing FASTA output"
usearch92 -fastq_filter ${SEQS_NAME} -fastq_maxee 1.0 -fastaout ${SEQS_NAME_FA} -threads 1 -fastq_ascii 33
usearch92 -fastq_filter ${CONTAMINANTS_NAME} -fastq_maxee 1.0 -fastaout ${CONTAMINANTS_NAME_FA} -threads 1 -fastq_ascii 33

echo "Done filtering all sequences, Begining the decontamination process"

if [ -s "${CONTAMINANTS_NAME_FA}" ]; then
  echo "Contaminant file exists: ${CONTAMINANTS_NAME}! Decontaminating now..."
	exclude_seqs_by_blast.py -i "${SEQS_NAME_FA}" -d "${CONTAMINANTS_NAME_FA}" -o "${SEQUENCE_DIR}decontaminated" -p 0.98
fi

echo "Decontamination done!"


echo "--------------------------------------------------"
echo "Script ends"
date
echo "--------------------------------------------------"
