#!/bin/bash
#$ -V
#$ -cwd
#$ -o logs/decontaminate_log.txt
#$ -j y
#$ -l mem_free=10G,h_vmem=20G
#$ -pe threaded 12

echo "--------------------------------------------------"
echo "Script starts"
date
echo "--------------------------------------------------"
source config.txt

module load qiime/1.9.1

SEQS_NAME=$1
CONTAMINANTS_NAME=$2

echo "Begining the filtering of all sequences, producing FASTA output"
usearch92 -fastq_filter ${SEQUENCE_DIR}${SEQS_NAME}.fq -fastq_maxee 1.0 -fastaout ${SEQUENCE_DIR}${SEQS_NAME}_filtered.fq -threads 1 -fastq_ascii 33
usearch92 -fastq_filter ${SEQUENCE_DIR}${CONTAMINANTS_NAME}.fq -fastq_maxee 1.0 -fastaout ${SEQUENCE_DIR}${CONTAMINANTS_NAME}_filtered.fq -threads 1 -fastq_ascii 33

echo "Done filtering all sequences, Begining the decontamination process"

if [ -s "${SEQUENCE_DIR}${CONTAMINANTS_NAME}_filtered.fq" ]; then
  echo "Contaminant file exists: ${CONTAMINANTS_NAME}! Decontaminating now..."
	exclude_seqs_by_blast.py -i "${SEQUENCE_DIR}${SEQS_NAME}_filtered.fq" -d "${SEQUENCE_DIR}${CONTAMINANTS_NAME}_filtered.fq" -o "${SEQUENCE_DIR}decontaminated" -p 0.98
fi

echo "Decontamination done!"


echo "--------------------------------------------------"
echo "Script ends"
date
echo "--------------------------------------------------"



#   qsub -N decont decontaminate.pbs
